### PR TITLE
Forgot initialize the platform. Each time when start GC v8 was crashed.

### PR DESCRIPTION
**Pull request by catap**
Somethings like

```
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000900bc1 in v8::internal::MarkCompactCollector::StartSweeperThreads() ()
(gdb) bt
#0  0x0000000000900bc1 in v8::internal::MarkCompactCollector::StartSweeperThreads() ()
#1  0x000000000090b8c8 in v8::internal::MarkCompactCollector::SweepSpaces() ()
#2  0x000000000091650c in v8::internal::MarkCompactCollector::CollectGarbage() ()
#3  0x00000000008d4796 in v8::internal::Heap::MarkCompact() ()
#4  0x00000000008ddc45 in v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) ()
#5  0x00000000008de078 in v8::internal::Heap::CollectGarbage(v8::internal::GarbageCollector, char const*, char const*, v8::GCCallbackFlags) ()
#6  0x00000000008de245 in v8::internal::Heap::CollectAllAvailableGarbage(char const*) ()
#7  0x000000000088dce5 in v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) ()
#8  0x000000000088e3c0 in v8::internal::Factory::NewStringFromUtf8(v8::internal::Vector<char const>, v8::internal::PretenureFlag) ()
#9  0x0000000000749d6c in v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::String::NewStringType, int) ()
#10 0x000000000071b96e in Cache::getScript (this=0x7fff71f70b80, filename=...) at src/cache.cc:168
```

### CODE REVIEW

**Comment by ondras** [comment]
Cool, thanks!

The SConstruct file is getting unmaintainably large. Would you be please so kind to briefly describe (via comments) the new command line flags used? I will try to refactor that into something smaller, perhaps slowly aiming for a Makefile.

Also, both `tea` and `libteajs.so` binaries are now extremely large (~25 megs). Any idea what causes this and how to evade it? V8 libs are rather tiny when compared to this (main v8 file is ~1.6M).

**Comment by catap** [comment]
Sure.

```
env_lib = env.Clone()
env_lib.Append(LINKFLAGS = ["-Wl,-undefined", "-Wl,dynamic_lookup"])
```

I must link all plugins with `-Wl,-undefined -Wl,dynamic_lookup`. I don't know the better way to do this that clone of env.

```
if env["os"] != "darwin":
    env.Append(LINKFLAGS = ["-Wl,--export-dynamic"])
    env.Append(_LIBFLAGS = ["-Wl,--whole-archive", "-Wl,--start-group"])
    env.Append(
        _LIBFLAGS= [env["v8_path"] + "/out/native/obj.target/tools/gyp/libv8_base.a",
            env["v8_path"] + "/out/native/obj.target/tools/gyp/libv8_libbase.a",
            env["v8_path"] + "/out/native/obj.target/tools/gyp/libv8_snapshot.a",
            env["v8_path"] + "/out/native/obj.target/tools/gyp/libv8_libplatform.a",
            env["v8_path"] + "/out/native/obj.target/third_party/icu/libicuuc.a",
            env["v8_path"] + "/out/native/obj.target/third_party/icu/libicui18n.a",
            env["v8_path"] + "/out/native/obj.target/third_party/icu/libicudata.a"]
        )
    env.Append(_LIBFLAGS = ["-Wl,--end-group", "-Wl,--no-whole-archive"])
else:
    env.Append(LINKFLAGS = ["-Wl,-export_dynamic", "-Wl,-all_load", "-fvisibility=default"])
    env.Append(
        _LIBFLAGS= [env["v8_path"] + "/out/native/libv8_base.a",
            env["v8_path"] + "/out/native/libv8_libbase.a",
            env["v8_path"] + "/out/native/libv8_snapshot.a",
            env["v8_path"] + "/out/native/libv8_libplatform.a",
            env["v8_path"] + "/out/native/libicuuc.a",
            env["v8_path"] + "/out/native/libicui18n.a",
            env["v8_path"] + "/out/native/libicudata.a"]
        )
```

On OS X and Linux v8 have different paths to `*.a` and different linker flag to create a static `tea` and `libtea`.

About size. Yes, `tea` and `libtia.so` really large, because this files include all v8 symbols:

```
➜  teajs git:(crash) du -shc deps/v8/out/native/*.a       
1.1M    deps/v8/out/native/libgmock.a
2.8M    deps/v8/out/native/libgtest.a
 10M    deps/v8/out/native/libicudata.a
 21M    deps/v8/out/native/libicui18n.a
 12M    deps/v8/out/native/libicuuc.a
464M    deps/v8/out/native/libv8_base.a
324K    deps/v8/out/native/libv8_libbase.a
260K    deps/v8/out/native/libv8_libplatform.a
1.7M    deps/v8/out/native/libv8_nosnapshot.a
2.7M    deps/v8/out/native/libv8_snapshot.a
516M    total
➜  teajs git:(crash) 
```

Sure, not so big likes a flat `.a` but biggest that was before static linked v8.

**Comment by ondras** [comment]
Well I still do not understand:

```
ondras@ondra:~/git/TeaJS/deps/v8/out/native/obj.target/tools/gyp$ du -shc *.a
1.6M    libv8_base.a
12K libv8_libbase.a
4.0K    libv8_libplatform.a
4.0K    libv8_nosnapshot.a
4.0K    libv8_snapshot.a
1.6M    total
```

Yet the `tea` binary has 23 megs...

**Comment by catap** [comment]
You also include libic*.a

**Comment by ondras** [comment]
```
ondras@ondra:~/git/TeaJS/deps/v8/out/native/obj.target/third_party/icu$ du -shc *.a
4.0K    libicudata.a
336K    libicui18n.a
164K    libicuuc.a
504K    total
```

Still not enough...

**Comment by catap** [comment]
It's depend of compiler/linker. For example when you have a static linked boost and other C++ stuff your bin file may have size up to gigs or biggest :)

For example on my OS X I have deps/v8/out/native/libv8_base.a with size 464 mb, but tea size is 27 Mb.

If you are interesting in I try to found some articles with explain this situation.

**Comment by ondras** [comment]
I would love to read some more about this. Also please note that nodejs apparently uses the same linking approach, yet their binary is few megs at most.

**Comment by catap** [comment]
Yes, node.js use same way to make a static linked binnary.

But by default node.js don't use a libicu with i18n support like tea.

```
➜  node git:(master) ./configure --with-icu-path=deps/v8/third_party/icu46/icu.gyp
...
➜  node git:(master) make
...
➜  node git:(master) ls -lh out/Release/node
-rwxr-xr-x+ 1 catap  staff    26M Jan 16 00:26 out/Release/node
➜  node git:(master) size out/Release/node  
__TEXT  __DATA  __OBJC  others  dec hex
20635648    520192  0   4300877824  4322033664  1019d0000
➜  node git:(master) 
```

and build without i18n:

```
➜  node git:(master) ./configure --with-icu-path=deps/v8/third_party/icu46/icu.gyp
...
➜  node git:(master) make
...
➜  node git:(master) ls -lh out/Release/node
-rwxr-xr-x+ 1 catap  staff    13M Jan 16 00:32 out/Release/node
➜  node git:(master) size out/Release/node  
__TEXT  __DATA  __OBJC  others  dec hex
8892416 421888  0   4299710464  4309024768  100d68000
➜  node git:(master) 
```

and tea on my laptop:

```
➜  teajs git:(master) ls -lh tea
-rwxr-xr-x+ 1 catap  staff    27M Jan 16 00:29 tea
➜  teajs git:(master) size tea
__TEXT  __DATA  __OBJC  others  dec hex
20688896    385024  0   4302176256  4323250176  101af9000
➜  teajs git:(master) 
```

Different is a size of `__TEXT` section where icu i18n include a lot of text strings.

I think best way add option `i18n` to scons what default switched off. What are you think about this?

**Comment by catap** [comment]
I implemented i18n=off for scons and have:

```
➜  teajs git:(i18n) ✗ ls -lh tea                                              
-rwxr-xr-x+ 1 catap  staff    12M Jan 16 01:03 tea
➜  teajs git:(i18n) ✗ size tea
__TEXT  __DATA  __OBJC  others  dec hex
7348224 262144  0   4300120064  4307730432  100c2c000
➜  teajs git:(i18n) ✗ 
```

You can try this way on branch catap/teajs@68e89c14c78319196c87cb264d9f4f453bf546da but I'm not sure about is good or bad.

**Comment by catap** [comment]
You can try this way on branch catap/teajs@68e89c14c78319196c87cb264d9f4f453bf546da but I'm not sure about is good or bad.

**Comment by ondras** [comment]
Interesting. I am definitely in favor of having this feature configurable. I will study what exactly does i18n support bring to the language...

**Comment by catap** [comment]
i18n is optional part of ECMAScript: http://wiki.ecmascript.org/doku.php?id=globalization:specification_drafts

My point is take it switched on by default and make a option to switch off when user prefer this way.

If you agree with my point, I can make a pull request.

**Comment by ondras** [comment]
Yes, I have no problem with your proposal of this feature being enabled by default.

**Pull request merged**
