### PR TITLE
Fix work on linux

### PR DESCRIPTION
**Pull request by catap**
Yes, os x still broken

### CODE REVIEW

**Comment by ondras** [comment]
Cool, will test soon. I believe that the Mac build shall be fiexed just by specifying proper compiler/linker flags...

**Comment by catap** [comment]
I hope so. :)

But I spend one day of my life to study how it works.

I also create a [small example](https://github.com/catap/dynamic-plugin-example) with two static libraries and dynamic load plugin.

My example works and teajs doesn't.

**Comment by ondras** [comment]
Interesting. Your Makefile exactly corresponds to the workflow I would expect to work (and it does - on Linux). Also, your Makefile looks like something I will build upon in order to switch the TeaJS build process from SCons to Make -- one day :-)

I noticed that your sample project's Darwin build uses the `-all_load` and `-noall_load` flags, something not present in your TeaJS build syntax. Also, does `nm` or `objdump` of the `tea` binary suggest that the missing symbol(s) - `__ZN2v87Isolate10GetCurrentEv` - are present?

**Comment by catap** [comment]
And my example works on OS X!

`noall_load` is for compatibility with old code:

```
ld: warning: option -noall_load is obsolete and being ignored
```

;)

**Pull request merged**
