### PR TITLE
Rewrite to new v8 API

### PR DESCRIPTION
**Pull request by catap**

### CODE REVIEW

**Comment by ondras** [comment]
Wow! I am, literally, completely amazed and very - VERY - pleased by this complex and useful patch. WOW again. :+1:

Approximately one year ago, I tried adapting TeaJS to recent V8 API myself - but the process was so frustrating I simply gave up. The current V8 API seems to be even more convoluted; kudos to your great work!

Before I (happily and eagerly) merge this huge PR, would you please mind explaining - in few short steps - what exactly has changed and why? I am familiar with _some_ API changes (mandatory isolates, persistent handles resetting, FunctionCallbackInfo signature), but the `CopyablePersistentTraits` is, for instance, very puzzling. Some of TeaJS's source is contributed and opaque for me, but I would like to remain fully aware of what and how the code does :-)

**Comment by catap** [comment]
Sure. But it's a lot of changes.

Main changes:
- Isolate. All object must associate with some Isolate. I just add one Isolate and use only this :)
- All objects what associated with `v8:HandleScope` will destroy when the `v8::HandleScope` will be destroyed.
- So, as effect last one change you can't return `v8::Handle` and you can return `v8:: Persistent` or use GetReturnValue like a all CallBack.
- You can't take access to Value of `v8::Persistent` by -> operator. Before you must associate the object with `v8::Handle` or `v8::Local` and take access by -> operator.
- `v8::Persistent` is unique identifier and when it can be copied your must setup `v8::CopyablePersistentTraits` as second argument of type. By default it is as `v8::NonCopyablePersistentTraits`.

It's a main idea of changes. I skipped some things like renamed methods :)

**Comment by ondras** [comment]
Smooth, thanks for explanation.

I am not sure if merging into master is the best way to go now; typical V8 versions in OS repositories are much lower (Ubuntu: 3.14.5). On the other hand, maintaining two versions of TeaJS is going to be painful. I wonder what approach is NodeJS taking here...

Finally: the patch you submitted implies that you have both formidable source code understanding skills as well as a thorough knowledge of current TeaJS code. Is there something relevant to TeaJS sources you would like to change, comment, adjust or similar? During your rewrite, have you encountered bugs, difficulties, potentially bad coding practices and so on? I must admit my C++ skills are far from being perfect...

**Comment by catap** [comment]
So, have a fork of v8 as submodule into TeaJS codes is a best way, I think so.

Because build a v8 is not easy, you must download dependencies, install google tools and do another steps. Not likes a `git clone ... && make` :)

But this isn't the main problem.

The main problem is a very active development mode and fast changes of API.

For example: since v8 3.20.8 (Jul 24 2013) the `v8::V8::Pause/ResumeProfiler` has been deprecated and was removed on v8 3.21.7 (Aug 30 2013).

Yes, only two month :)

And when you haven't a stable API in project, use fork of this project as submodules looks best way, don't it?

About the code and bugs.
So. I don't like C++ so much but your C++ code is easy for understanding that v8 code for example. Bugs.

**Comment by ondras** [comment]
Well, I was trying to hide the complexity of the V8 building process by leveraging the system-wide libv8 package where applicable. This approach, however, locks me with the old V8 API available in standard packages.

The submodule idea is nice. I see one issue here: I use Mercurial as my primary tool for TeaJS revision control; GitHub is only synced via hg-git bridge. I am not sure submodules are going to be compatible Git/Mercurial-wise. I will have a look into that.

In the meantime, I am considering merging this pull request into a branch and perhaps switching to Git altogether?

**Comment by catap** [comment]
A submodule isn't a silver bullet :)

You can't clone v8 repository and just make it. You must fetch few sources from svn with specialised revision and put it to specified folder or use make dependencies but it required install gclient.

I think best practices is a folder and some times syncing from original v8 tree.

Switching to git and use Github as social development platform is the best way for me ;)

**Comment by ondras** [comment]
Sounds reasonable. Would you also suggest using a statically linked V8 instead?

Also, what do you think about moving from SCons to GNU Make? Scons was useful when V8 was built with it - that is no longer true...

**Comment by catap** [comment]
Yes, statically linked V8 must to simplify to use the TeaJS. But build script will be very complicated.

Change SCons to GNU Make? I don't know, really. I think for do this you need change building system to gyp-based and GNU Make is easy because have a example — node.js :)

I'll check it tomorrow and may I can make a small patch to include v8 to TeaJS sources tree.

**Comment by ondras** [comment]
Thanks for your valuable opinions and contributions. I am merging your super-large patch now :-)

**Comment by ondras** [comment]
Hmm, something is not right:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff52a863f in v8::internal::Object::GetElementWithReceiver(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, unsigned int) ()
   from /home/ondras/git/TeaJS/lib/fs.so
(gdb) bt
#0  0x00007ffff52a863f in v8::internal::Object::GetElementWithReceiver(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, unsigned int)
    () from /home/ondras/git/TeaJS/lib/fs.so
#1  0x00007ffff5125331 in v8::internal::Execution::InstantiateFunction(v8::internal::Handle<v8::internal::FunctionTemplateInfo>) () from /home/ondras/git/TeaJS/lib/fs.so
#2  0x00007ffff50a34df in v8::FunctionTemplate::GetFunction() () from /home/ondras/git/TeaJS/lib/fs.so
#3  0x00007ffff50844ae in init () from /home/ondras/git/TeaJS/lib/fs.so
#4  0x0000000000412225 in TeaJS_App::load_dso(std::string, v8::Handle<v8::Function>, v8::Handle<v8::Object>, v8::Handle<v8::Object>) ()
#5  0x0000000000414986 in TeaJS_App::require(std::string, std::string) ()
#6  0x00000000004151fe in _require(v8::FunctionCallbackInfo<v8::Value> const&) ()
#7  0x000000000075e799 in v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) ()
#8  0x0000000000452493 in v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) ()
```

(attempt to run `./tea unit/runner`)

Do you have any idea what might have gone wrong? The same happens when trying to load any other native/binary module.

**Comment by catap** [comment]
nope.

I'll check it

**Comment by catap** [comment]
So, I found the problem.

TeaJS use a dynamic linking modules like the `fs.so`.

Modules is linked with v8 static libraries and also `tea` linked with v8 static libraries.

And the stack is broken when TeaJS load `fs.so` by `require("fs")`

So, I need more time to looking for solution, yeah.

**Comment by ondras** [comment]
I see. Well, do the modules need to be linked with libv8?

**Comment by catap** [comment]
Correct.

You can't assembly a library without information about missing symbols. You can mark it as linked with some library or include inside into the library.

Fast way that I know:
- remove a static linking.
- remove dynamic linking modules who linking with v8.

I may found another way tomorrow, but I'm not sure.

**Comment by catap** [comment]
So, I have one funny way.

I can create a `libteajs_v8.so` and linking all modules with this.

What do you think about it?

**Comment by ondras** [comment]
Interesting options. The last variant - libteajs_v8.so - would require a small binary that would just dlopen the libteajs_v8.so and run its main() ? Or what could would you compile into libteajs_v8.so?

This is what I read in nodejs's docs at http://nodejs.org/api/addons.html: 

```
Node statically compiles all its dependencies into the executable. When compiling your module, you don't need to worry about linking to any of these libraries. 
```

So apparently the static-linking approach _is_ possible, but maybe hard to get right?

**Comment by ondras** [comment]
Also, this is perhaps relevant: http://stackoverflow.com/questions/14917406/shared-library-using-v8-is-incompatible-with-statically-linked-v8

**Comment by ondras** [comment]
So, from what I understand:

1) the main binary needs to be statically linked to libv8.a
2) the main binary needs to export all V8 symbols
3) all loadable modules are compiled without V8, so they find their missing symbols at runtime, provided by the main binary.

Is this a complete nonsense or not?

**Comment by ondras** [comment]
Last link for today, I promise! :-)
http://stackoverflow.com/questions/3623375/shared-object-cant-find-symbols-in-main-binary-c

**Comment by catap** [comment]
Yes, I try do this but I have some issue on OS X:

```
➜  teajs git:(static_v8) ✗ g++-4.9 -o lib/binary.dylib -pg -dynamiclib src/lib/binary/binary.os src/lib/binary/bytestorage.os -liconv -Wl,-undefined -Wl,dynamic_lookup
➜  teajs git:(static_v8) ✗ g++-4.9 -o tea -pg src/common.os src/system.os src/cache.os src/gc.os src/app.os src/path.os src/lib/binary/bytestorage.os src/teajs.o -liconv -liconv deps/v8/out/native/libv8_base.a deps/v8/out/native/libv8_libbase.a deps/v8/out/native/libv8_snapshot.a deps/v8/out/native/libv8_libplatform.a deps/v8/out/native/libicuuc.a deps/v8/out/native/libicui18n.a deps/v8/out/native/libicudata.a -Wl,-export_dynamic           
➜  teajs git:(static_v8) ✗ cat test.js 
var fs = require("binary");

➜  teajs git:(static_v8) ✗ ./tea test.js 
dyld: lazy symbol binding failed: Symbol not found: __ZN2v87Isolate10GetCurrentEv
  Referenced from: /Users/catap/Documents/OpenSource/teajs/teajs/lib/binary.dylib
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v87Isolate10GetCurrentEv
  Referenced from: /Users/catap/Documents/OpenSource/teajs/teajs/lib/binary.dylib
  Expected in: flat namespace

[1]    23261 trace trap  ./tea test.js
➜  teajs git:(static_v8) ✗ 
```

But I fix it on linux:

```
catap@ubuntu:~/teajs$ ./tea unit/runner.js unit/tests
test_unit/tests:
    test_unit/tests/sqlite.js:
        testSQLite
    test_unit/tests/dom.js:
        testAppend
        testInsert
        testSerialize
        testClone
        testParse
        testBadEntities
        testIssue65
        testFragInsert0
        testFragAppend
    test_unit/tests/exif.js:
        testReader
    test_unit/tests/html.js:
        testHtml
    test_unit/tests/zlib.js:
        testZlib
    test_unit/tests/base64.js:
        testBase64encode
        testBase64decode
    test_unit/tests/require.js:
        testRelative
    test_unit/tests/js.js:
        testString
        testDate
    test_unit/tests/assert.js:
        testEqual
        testOK
        testNotEqual
        testStrictEqual
        testNotStrictEqual
        testThrows
        testDeepEqual
        testNotDeepEqual
    test_unit/tests/template.js:
        testTemplate
    test_unit/tests/getopt.js:
        testGetoptInitial
        testGetoptErrors
        testGetoptOk
        testGetoptMain
        testIssue17
        testIssue7
    test_unit/tests/fs.js:
        testFile
        testDirectory
        testReadWriteLine
    test_unit/tests/hash.js:
        testMD5
        testSHA1
    test_unit/tests/binary.js:
        testBuffer
        testRange
        testToString
RESULTS:
    passed: 41
    failed: 0
    errors: 0

Test run was successful!
catap@ubuntu:~/teajs$ 
```

**Comment by ondras** [comment]
Perhaps some (MacOSX-related) hints can be found in nodejs's GYP configuration: https://github.com/joyent/node/blob/master/common.gypi

But the Linux success looks very nice!

**Pull request merged**
